export type CountryDialCode = {
  iso: string
  code: string
  flag: string
  name: string
  nameAr: string
}

export const countryCodes: CountryDialCode[] = [
  // Primary regional countries first
  { iso: "IQ", code: "+964", flag: "🇮🇶", name: "Iraq", nameAr: "العراق" },
  { iso: "AE", code: "+971", flag: "🇦🇪", name: "United Arab Emirates", nameAr: "الإمارات" },
  { iso: "SA", code: "+966", flag: "🇸🇦", name: "Saudi Arabia", nameAr: "السعودية" },
  { iso: "KW", code: "+965", flag: "🇰🇼", name: "Kuwait", nameAr: "الكويت" },
  { iso: "QA", code: "+974", flag: "🇶🇦", name: "Qatar", nameAr: "قطر" },
  { iso: "BH", code: "+973", flag: "🇧🇭", name: "Bahrain", nameAr: "البحرين" },
  { iso: "OM", code: "+968", flag: "🇴🇲", name: "Oman", nameAr: "عُمان" },
  { iso: "JO", code: "+962", flag: "🇯🇴", name: "Jordan", nameAr: "الأردن" },
  { iso: "LB", code: "+961", flag: "🇱🇧", name: "Lebanon", nameAr: "لبنان" },
  { iso: "SY", code: "+963", flag: "🇸🇾", name: "Syria", nameAr: "سوريا" },
  { iso: "PS", code: "+970", flag: "🇵🇸", name: "Palestine", nameAr: "فلسطين" },
  { iso: "EG", code: "+20", flag: "🇪🇬", name: "Egypt", nameAr: "مصر" },
  { iso: "TR", code: "+90", flag: "🇹🇷", name: "Turkey", nameAr: "تركيا" },
  { iso: "IR", code: "+98", flag: "🇮🇷", name: "Iran", nameAr: "إيران" },
  { iso: "YE", code: "+967", flag: "🇾🇪", name: "Yemen", nameAr: "اليمن" },
  { iso: "LY", code: "+218", flag: "🇱🇾", name: "Libya", nameAr: "ليبيا" },
  { iso: "TN", code: "+216", flag: "🇹🇳", name: "Tunisia", nameAr: "تونس" },
  { iso: "DZ", code: "+213", flag: "🇩🇿", name: "Algeria", nameAr: "الجزائر" },
  { iso: "MA", code: "+212", flag: "🇲🇦", name: "Morocco", nameAr: "المغرب" },
  { iso: "SD", code: "+249", flag: "🇸🇩", name: "Sudan", nameAr: "السودان" },

  // Rest of the world (alphabetical)
  { iso: "AF", code: "+93", flag: "🇦🇫", name: "Afghanistan", nameAr: "أفغانستان" },
  { iso: "AL", code: "+355", flag: "🇦🇱", name: "Albania", nameAr: "ألبانيا" },
  { iso: "AD", code: "+376", flag: "🇦🇩", name: "Andorra", nameAr: "أندورا" },
  { iso: "AO", code: "+244", flag: "🇦🇴", name: "Angola", nameAr: "أنغولا" },
  { iso: "AG", code: "+1-268", flag: "🇦🇬", name: "Antigua and Barbuda", nameAr: "أنتيغوا وبربودا" },
  { iso: "AR", code: "+54", flag: "🇦🇷", name: "Argentina", nameAr: "الأرجنتين" },
  { iso: "AM", code: "+374", flag: "🇦🇲", name: "Armenia", nameAr: "أرمينيا" },
  { iso: "AU", code: "+61", flag: "🇦🇺", name: "Australia", nameAr: "أستراليا" },
  { iso: "AT", code: "+43", flag: "🇦🇹", name: "Austria", nameAr: "النمسا" },
  { iso: "AZ", code: "+994", flag: "🇦🇿", name: "Azerbaijan", nameAr: "أذربيجان" },
  { iso: "BS", code: "+1-242", flag: "🇧🇸", name: "Bahamas", nameAr: "البهاما" },
  { iso: "BD", code: "+880", flag: "🇧🇩", name: "Bangladesh", nameAr: "بنغلاديش" },
  { iso: "BB", code: "+1-246", flag: "🇧🇧", name: "Barbados", nameAr: "باربادوس" },
  { iso: "BY", code: "+375", flag: "🇧🇾", name: "Belarus", nameAr: "بيلاروسيا" },
  { iso: "BE", code: "+32", flag: "🇧🇪", name: "Belgium", nameAr: "بلجيكا" },
  { iso: "BZ", code: "+501", flag: "🇧🇿", name: "Belize", nameAr: "بليز" },
  { iso: "BJ", code: "+229", flag: "🇧🇯", name: "Benin", nameAr: "بنين" },
  { iso: "BT", code: "+975", flag: "🇧🇹", name: "Bhutan", nameAr: "بوتان" },
  { iso: "BO", code: "+591", flag: "🇧🇴", name: "Bolivia", nameAr: "بوليفيا" },
  { iso: "BA", code: "+387", flag: "🇧🇦", name: "Bosnia and Herzegovina", nameAr: "البوسنة والهرسك" },
  { iso: "BW", code: "+267", flag: "🇧🇼", name: "Botswana", nameAr: "بوتسوانا" },
  { iso: "BR", code: "+55", flag: "🇧🇷", name: "Brazil", nameAr: "البرازيل" },
  { iso: "BN", code: "+673", flag: "🇧🇳", name: "Brunei", nameAr: "بروناي" },
  { iso: "BG", code: "+359", flag: "🇧🇬", name: "Bulgaria", nameAr: "بلغاريا" },
  { iso: "BF", code: "+226", flag: "🇧🇫", name: "Burkina Faso", nameAr: "بوركينا فاسو" },
  { iso: "BI", code: "+257", flag: "🇧🇮", name: "Burundi", nameAr: "بوروندي" },
  { iso: "KH", code: "+855", flag: "🇰🇭", name: "Cambodia", nameAr: "كمبوديا" },
  { iso: "CM", code: "+237", flag: "🇨🇲", name: "Cameroon", nameAr: "الكاميرون" },
  { iso: "CA", code: "+1", flag: "🇨🇦", name: "Canada", nameAr: "كندا" },
  { iso: "CV", code: "+238", flag: "🇨🇻", name: "Cape Verde", nameAr: "الرأس الأخضر" },
  { iso: "CF", code: "+236", flag: "🇨🇫", name: "Central African Republic", nameAr: "جمهورية أفريقيا الوسطى" },
  { iso: "TD", code: "+235", flag: "🇹🇩", name: "Chad", nameAr: "تشاد" },
  { iso: "CL", code: "+56", flag: "🇨🇱", name: "Chile", nameAr: "تشيلي" },
  { iso: "CN", code: "+86", flag: "🇨🇳", name: "China", nameAr: "الصين" },
  { iso: "CO", code: "+57", flag: "🇨🇴", name: "Colombia", nameAr: "كولومبيا" },
  { iso: "KM", code: "+269", flag: "🇰🇲", name: "Comoros", nameAr: "جزر القمر" },
  { iso: "CG", code: "+242", flag: "🇨🇬", name: "Congo", nameAr: "الكونغو" },
  { iso: "CD", code: "+243", flag: "🇨🇩", name: "DR Congo", nameAr: "جمهورية الكونغو الديمقراطية" },
  { iso: "CR", code: "+506", flag: "🇨🇷", name: "Costa Rica", nameAr: "كوستاريكا" },
  { iso: "HR", code: "+385", flag: "🇭🇷", name: "Croatia", nameAr: "كرواتيا" },
  { iso: "CU", code: "+53", flag: "🇨🇺", name: "Cuba", nameAr: "كوبا" },
  { iso: "CY", code: "+357", flag: "🇨🇾", name: "Cyprus", nameAr: "قبرص" },
  { iso: "CZ", code: "+420", flag: "🇨🇿", name: "Czech Republic", nameAr: "التشيك" },
  { iso: "DK", code: "+45", flag: "🇩🇰", name: "Denmark", nameAr: "الدنمارك" },
  { iso: "DJ", code: "+253", flag: "🇩🇯", name: "Djibouti", nameAr: "جيبوتي" },
  { iso: "DM", code: "+1-767", flag: "🇩🇲", name: "Dominica", nameAr: "دومينيكا" },
  { iso: "DO", code: "+1-809", flag: "🇩🇴", name: "Dominican Republic", nameAr: "جمهورية الدومينيكان" },
  { iso: "EC", code: "+593", flag: "🇪🇨", name: "Ecuador", nameAr: "الإكوادور" },
  { iso: "SV", code: "+503", flag: "🇸🇻", name: "El Salvador", nameAr: "السلفادور" },
  { iso: "GQ", code: "+240", flag: "🇬🇶", name: "Equatorial Guinea", nameAr: "غينيا الاستوائية" },
  { iso: "ER", code: "+291", flag: "🇪🇷", name: "Eritrea", nameAr: "إريتريا" },
  { iso: "EE", code: "+372", flag: "🇪🇪", name: "Estonia", nameAr: "إستونيا" },
  { iso: "ET", code: "+251", flag: "🇪🇹", name: "Ethiopia", nameAr: "إثيوبيا" },
  { iso: "FJ", code: "+679", flag: "🇫🇯", name: "Fiji", nameAr: "فيجي" },
  { iso: "FI", code: "+358", flag: "🇫🇮", name: "Finland", nameAr: "فنلندا" },
  { iso: "FR", code: "+33", flag: "🇫🇷", name: "France", nameAr: "فرنسا" },
  { iso: "GA", code: "+241", flag: "🇬🇦", name: "Gabon", nameAr: "الغابون" },
  { iso: "GM", code: "+220", flag: "🇬🇲", name: "Gambia", nameAr: "غامبيا" },
  { iso: "GE", code: "+995", flag: "🇬🇪", name: "Georgia", nameAr: "جورجيا" },
  { iso: "DE", code: "+49", flag: "🇩🇪", name: "Germany", nameAr: "ألمانيا" },
  { iso: "GH", code: "+233", flag: "🇬🇭", name: "Ghana", nameAr: "غانا" },
  { iso: "GR", code: "+30", flag: "🇬🇷", name: "Greece", nameAr: "اليونان" },
  { iso: "GD", code: "+1-473", flag: "🇬🇩", name: "Grenada", nameAr: "غرينادا" },
  { iso: "GT", code: "+502", flag: "🇬🇹", name: "Guatemala", nameAr: "غواتيمالا" },
  { iso: "GN", code: "+224", flag: "🇬🇳", name: "Guinea", nameAr: "غينيا" },
  { iso: "GW", code: "+245", flag: "🇬🇼", name: "Guinea-Bissau", nameAr: "غينيا بيساو" },
  { iso: "GY", code: "+592", flag: "🇬🇾", name: "Guyana", nameAr: "غيانا" },
  { iso: "HT", code: "+509", flag: "🇭🇹", name: "Haiti", nameAr: "هايتي" },
  { iso: "HN", code: "+504", flag: "🇭🇳", name: "Honduras", nameAr: "هندوراس" },
  { iso: "HK", code: "+852", flag: "🇭🇰", name: "Hong Kong", nameAr: "هونغ كونغ" },
  { iso: "HU", code: "+36", flag: "🇭🇺", name: "Hungary", nameAr: "المجر" },
  { iso: "IS", code: "+354", flag: "🇮🇸", name: "Iceland", nameAr: "آيسلندا" },
  { iso: "IN", code: "+91", flag: "🇮🇳", name: "India", nameAr: "الهند" },
  { iso: "ID", code: "+62", flag: "🇮🇩", name: "Indonesia", nameAr: "إندونيسيا" },
  { iso: "IE", code: "+353", flag: "🇮🇪", name: "Ireland", nameAr: "أيرلندا" },
  { iso: "IT", code: "+39", flag: "🇮🇹", name: "Italy", nameAr: "إيطاليا" },
  { iso: "CI", code: "+225", flag: "🇨🇮", name: "Ivory Coast", nameAr: "ساحل العاج" },
  { iso: "JM", code: "+1-876", flag: "🇯🇲", name: "Jamaica", nameAr: "جامايكا" },
  { iso: "JP", code: "+81", flag: "🇯🇵", name: "Japan", nameAr: "اليابان" },
  { iso: "KZ", code: "+7", flag: "🇰🇿", name: "Kazakhstan", nameAr: "كازاخستان" },
  { iso: "KE", code: "+254", flag: "🇰🇪", name: "Kenya", nameAr: "كينيا" },
  { iso: "KI", code: "+686", flag: "🇰🇮", name: "Kiribati", nameAr: "كيريباتي" },
  { iso: "KP", code: "+850", flag: "🇰🇵", name: "North Korea", nameAr: "كوريا الشمالية" },
  { iso: "KR", code: "+82", flag: "🇰🇷", name: "South Korea", nameAr: "كوريا الجنوبية" },
  { iso: "KG", code: "+996", flag: "🇰🇬", name: "Kyrgyzstan", nameAr: "قيرغيزستان" },
  { iso: "LA", code: "+856", flag: "🇱🇦", name: "Laos", nameAr: "لاوس" },
  { iso: "LV", code: "+371", flag: "🇱🇻", name: "Latvia", nameAr: "لاتفيا" },
  { iso: "LS", code: "+266", flag: "🇱🇸", name: "Lesotho", nameAr: "ليسوتو" },
  { iso: "LR", code: "+231", flag: "🇱🇷", name: "Liberia", nameAr: "ليبيريا" },
  { iso: "LI", code: "+423", flag: "🇱🇮", name: "Liechtenstein", nameAr: "ليختنشتاين" },
  { iso: "LT", code: "+370", flag: "🇱🇹", name: "Lithuania", nameAr: "ليتوانيا" },
  { iso: "LU", code: "+352", flag: "🇱🇺", name: "Luxembourg", nameAr: "لوكسمبورغ" },
  { iso: "MO", code: "+853", flag: "🇲🇴", name: "Macau", nameAr: "ماكاو" },
  { iso: "MK", code: "+389", flag: "🇲🇰", name: "North Macedonia", nameAr: "مقدونيا الشمالية" },
  { iso: "MG", code: "+261", flag: "🇲🇬", name: "Madagascar", nameAr: "مدغشقر" },
  { iso: "MW", code: "+265", flag: "🇲🇼", name: "Malawi", nameAr: "مالاوي" },
  { iso: "MY", code: "+60", flag: "🇲🇾", name: "Malaysia", nameAr: "ماليزيا" },
  { iso: "MV", code: "+960", flag: "🇲🇻", name: "Maldives", nameAr: "المالديف" },
  { iso: "ML", code: "+223", flag: "🇲🇱", name: "Mali", nameAr: "مالي" },
  { iso: "MT", code: "+356", flag: "🇲🇹", name: "Malta", nameAr: "مالطا" },
  { iso: "MR", code: "+222", flag: "🇲🇷", name: "Mauritania", nameAr: "موريتانيا" },
  { iso: "MU", code: "+230", flag: "🇲🇺", name: "Mauritius", nameAr: "موريشيوس" },
  { iso: "MX", code: "+52", flag: "🇲🇽", name: "Mexico", nameAr: "المكسيك" },
  { iso: "MD", code: "+373", flag: "🇲🇩", name: "Moldova", nameAr: "مولدوفا" },
  { iso: "MC", code: "+377", flag: "🇲🇨", name: "Monaco", nameAr: "موناكو" },
  { iso: "MN", code: "+976", flag: "🇲🇳", name: "Mongolia", nameAr: "منغوليا" },
  { iso: "ME", code: "+382", flag: "🇲🇪", name: "Montenegro", nameAr: "الجبل الأسود" },
  { iso: "MZ", code: "+258", flag: "🇲🇿", name: "Mozambique", nameAr: "موزمبيق" },
  { iso: "MM", code: "+95", flag: "🇲🇲", name: "Myanmar", nameAr: "ميانمار" },
  { iso: "NA", code: "+264", flag: "🇳🇦", name: "Namibia", nameAr: "ناميبيا" },
  { iso: "NP", code: "+977", flag: "🇳🇵", name: "Nepal", nameAr: "نيبال" },
  { iso: "NL", code: "+31", flag: "🇳🇱", name: "Netherlands", nameAr: "هولندا" },
  { iso: "NZ", code: "+64", flag: "🇳🇿", name: "New Zealand", nameAr: "نيوزيلندا" },
  { iso: "NI", code: "+505", flag: "🇳🇮", name: "Nicaragua", nameAr: "نيكاراغوا" },
  { iso: "NE", code: "+227", flag: "🇳🇪", name: "Niger", nameAr: "النيجر" },
  { iso: "NG", code: "+234", flag: "🇳🇬", name: "Nigeria", nameAr: "نيجيريا" },
  { iso: "NO", code: "+47", flag: "🇳🇴", name: "Norway", nameAr: "النرويج" },
  { iso: "PK", code: "+92", flag: "🇵🇰", name: "Pakistan", nameAr: "باكستان" },
  { iso: "PA", code: "+507", flag: "🇵🇦", name: "Panama", nameAr: "بنما" },
  { iso: "PG", code: "+675", flag: "🇵🇬", name: "Papua New Guinea", nameAr: "بابوا غينيا الجديدة" },
  { iso: "PY", code: "+595", flag: "🇵🇾", name: "Paraguay", nameAr: "باراغواي" },
  { iso: "PE", code: "+51", flag: "🇵🇪", name: "Peru", nameAr: "بيرو" },
  { iso: "PH", code: "+63", flag: "🇵🇭", name: "Philippines", nameAr: "الفلبين" },
  { iso: "PL", code: "+48", flag: "🇵🇱", name: "Poland", nameAr: "بولندا" },
  { iso: "PT", code: "+351", flag: "🇵🇹", name: "Portugal", nameAr: "البرتغال" },
  { iso: "RO", code: "+40", flag: "🇷🇴", name: "Romania", nameAr: "رومانيا" },
  { iso: "RU", code: "+7", flag: "🇷🇺", name: "Russia", nameAr: "روسيا" },
  { iso: "RW", code: "+250", flag: "🇷🇼", name: "Rwanda", nameAr: "رواندا" },
  { iso: "SN", code: "+221", flag: "🇸🇳", name: "Senegal", nameAr: "السنغال" },
  { iso: "RS", code: "+381", flag: "🇷🇸", name: "Serbia", nameAr: "صربيا" },
  { iso: "SG", code: "+65", flag: "🇸🇬", name: "Singapore", nameAr: "سنغافورة" },
  { iso: "SK", code: "+421", flag: "🇸🇰", name: "Slovakia", nameAr: "سلوفاكيا" },
  { iso: "SI", code: "+386", flag: "🇸🇮", name: "Slovenia", nameAr: "سلوفينيا" },
  { iso: "SO", code: "+252", flag: "🇸🇴", name: "Somalia", nameAr: "الصومال" },
  { iso: "ZA", code: "+27", flag: "🇿🇦", name: "South Africa", nameAr: "جنوب أفريقيا" },
  { iso: "SS", code: "+211", flag: "🇸🇸", name: "South Sudan", nameAr: "جنوب السودان" },
  { iso: "ES", code: "+34", flag: "🇪🇸", name: "Spain", nameAr: "إسبانيا" },
  { iso: "LK", code: "+94", flag: "🇱🇰", name: "Sri Lanka", nameAr: "سريلانكا" },
  { iso: "SE", code: "+46", flag: "🇸🇪", name: "Sweden", nameAr: "السويد" },
  { iso: "CH", code: "+41", flag: "🇨🇭", name: "Switzerland", nameAr: "سويسرا" },
  { iso: "TW", code: "+886", flag: "🇹🇼", name: "Taiwan", nameAr: "تايوان" },
  { iso: "TJ", code: "+992", flag: "🇹🇯", name: "Tajikistan", nameAr: "طاجيكستان" },
  { iso: "TZ", code: "+255", flag: "🇹🇿", name: "Tanzania", nameAr: "تنزانيا" },
  { iso: "TH", code: "+66", flag: "🇹🇭", name: "Thailand", nameAr: "تايلاند" },
  { iso: "TG", code: "+228", flag: "🇹🇬", name: "Togo", nameAr: "توغو" },
  { iso: "TT", code: "+1-868", flag: "🇹🇹", name: "Trinidad and Tobago", nameAr: "ترينيداد وتوباغو" },
  { iso: "UG", code: "+256", flag: "🇺🇬", name: "Uganda", nameAr: "أوغندا" },
  { iso: "UA", code: "+380", flag: "🇺🇦", name: "Ukraine", nameAr: "أوكرانيا" },
  { iso: "GB", code: "+44", flag: "🇬🇧", name: "United Kingdom", nameAr: "المملكة المتحدة" },
  { iso: "US", code: "+1", flag: "🇺🇸", name: "United States", nameAr: "الولايات المتحدة" },
  { iso: "UY", code: "+598", flag: "🇺🇾", name: "Uruguay", nameAr: "أوروغواي" },
  { iso: "UZ", code: "+998", flag: "🇺🇿", name: "Uzbekistan", nameAr: "أوزبكستان" },
  { iso: "VE", code: "+58", flag: "🇻🇪", name: "Venezuela", nameAr: "فنزويلا" },
  { iso: "VN", code: "+84", flag: "🇻🇳", name: "Vietnam", nameAr: "فيتنام" },
  { iso: "ZM", code: "+260", flag: "🇿🇲", name: "Zambia", nameAr: "زامبيا" },
  { iso: "ZW", code: "+263", flag: "🇿🇼", name: "Zimbabwe", nameAr: "زيمبابوي" },
]
